services:
  - type: web
    name: keycap-backend
    runtime: docker
    plan: free
    region: singapore
    healthCheckPath: /actuator/health
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: keycap-postgres
          property: connectionString
      - key: SPRING_DATASOURCE_USERNAME
        fromDatabase:
          name: keycap-postgres
          property: user
      - key: SPRING_DATASOURCE_PASSWORD
        fromDatabase:
          name: keycap-postgres
          property: password
      - key: JWT_SECRET
        generateValue: true
      - key: JPA_DDL_AUTO
        value: update
      - key: FRONTEND_URL
        sync: false
      - key: APP_CORS_ALLOWED_ORIGINS
        sync: false
      - key: GOOGLE_CLIENT_ID
        sync: false
      - key: GOOGLE_CLIENT_SECRET
        sync: false
      - key: CLOUDINARY_CLOUD_NAME
        sync: false
      - key: CLOUDINARY_API_KEY
        sync: false
      - key: CLOUDINARY_API_SECRET
        sync: false
      - key: PAYOS_CLIENT_ID
        sync: false
      - key: PAYOS_API_KEY
        sync: false
      - key: PAYOS_CHECKSUM_KEY
        sync: false

databases:
  - name: keycap-postgres
    plan: free
    region: singapore
    postgresMajorVersion: "18"
    databaseName: keycap_design
    user: keycap_app
    ipAllowList: []
